var states = {};
states = [
{"name":"Alabama","abbr":"AL","capital":"Montgomery","most-populous-city":"Birmingham","population":"4708708","square-miles":"52423","time-zone-1":"CST (UTC-6)","time-zone-2":"EST (UTC-5)","dst":"YES"},
{"name":"Alaska","abbr":"AK","capital":"Juneau","most-populous-city":"Anchorage","population":"698473","square-miles":"656425","time-zone-1":"AKST (UTC-09)","time-zone-2":"HST (UTC-10)","dst":"YES"},
{"name":"Arizona","abbr":"AZ","capital":"Phoenix","most-populous-city":"Phoenix","population":"6595778","square-miles":"114006","time-zone-1":"MT (UTC-07)","time-zone-2":"","dst":"NO"},
{"name":"Arkansas","abbr":"AR","capital":"Little Rock","most-populous-city":"Little Rock","population":"2889450","square-miles":"53182","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"California","abbr":"CA","capital":"Sacramento","most-populous-city":"Los Angeles","population":"36961664","square-miles":"163707","time-zone-1":"PT (UTC-8)","time-zone-2":"","dst":"YES"},
{"name":"Colorado","abbr":"CO","capital":"Denver","most-populous-city":"Denver","population":"5024748","square-miles":"104100","time-zone-1":"MT (UTC-07)","time-zone-2":"","dst":"YES"},
{"name":"Connecticut","abbr":"CT","capital":"Hartford","most-populous-city":"Bridgeport","population":"3518288","square-miles":"5544","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Delaware","abbr":"DE","capital":"Dover","most-populous-city":"Wilmington","population":"885122","square-miles":"1954","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Florida","abbr":"FL","capital":"Tallahassee","most-populous-city":"Jacksonville","population":"18537969","square-miles":"65758","time-zone-1":"EST (UTC-5)","time-zone-2":"CST (UTC-6)","dst":"YES"},
{"name":"Georgia","abbr":"GA","capital":"Atlanta","most-populous-city":"Atlanta","population":"9829211","square-miles":"59441","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Hawaii","abbr":"HI","capital":"Honolulu","most-populous-city":"Honolulu","population":"1295178","square-miles":"10932","time-zone-1":"HST (UTC-10)","time-zone-2":"","dst":"NO"},
{"name":"Idaho","abbr":"ID","capital":"Boise","most-populous-city":"Boise","population":"1545801","square-miles":"83574","time-zone-1":"MT (UTC-07)","time-zone-2":"PT (UTC-8)","dst":"YES"},
{"name":"Illinois","abbr":"IL","capital":"Springfield","most-populous-city":"Chicago","population":"12910409","square-miles":"57918","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"Indiana","abbr":"IN","capital":"Indianapolis","most-populous-city":"Indianapolis","population":"6423113","square-miles":"36420","time-zone-1":"EST (UTC-5)","time-zone-2":"CST (UTC-6)","dst":"YES"},
{"name":"Iowa","abbr":"IA","capital":"Des Moines","most-populous-city":"Des Moines","population":"3007856","square-miles":"56276","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"Kansas","abbr":"KS","capital":"Topeka","most-populous-city":"Wichita","population":"2818747","square-miles":"82282","time-zone-1":"CST (UTC-6)","time-zone-2":"MT (UTC-07)","dst":"YES"},
{"name":"Kentucky","abbr":"KY","capital":"Frankfort","most-populous-city":"Louisville","population":"4314113","square-miles":"40411","time-zone-1":"EST (UTC-5)","time-zone-2":"CST (UTC-6)","dst":"YES"},
{"name":"Louisiana","abbr":"LA","capital":"Baton Rouge","most-populous-city":"New Orleans","population":"4492076","square-miles":"51843","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"Maine","abbr":"ME","capital":"Augusta","most-populous-city":"Portland","population":"1318301","square-miles":"35387","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Maryland","abbr":"MD","capital":"Annapolis","most-populous-city":"Baltimore","population":"5699478","square-miles":"12407","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Massachusetts","abbr":"MA","capital":"Boston","most-populous-city":"Boston","population":"6593587","square-miles":"10555","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Michigan","abbr":"MI","capital":"Lansing","most-populous-city":"Detroit","population":"9969727","square-miles":"96810","time-zone-1":"EST (UTC-5)","time-zone-2":"CST (UTC-6)","dst":"YES"},
{"name":"Minnesota","abbr":"MN","capital":"Saint Paul","most-populous-city":"Minneapolis","population":"5266214","square-miles":"86943","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"Mississippi","abbr":"MS","capital":"Jackson","most-populous-city":"Jackson","population":"2951996","square-miles":"48434","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"Missouri","abbr":"MO","capital":"Jefferson City","most-populous-city":"Kansas City","population":"5987580","square-miles":"69709","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"Montana","abbr":"MT","capital":"Helena","most-populous-city":"Billings","population":"974989","square-miles":"147046","time-zone-1":"MT (UTC-07)","time-zone-2":"","dst":"YES"},
{"name":"Nebraska","abbr":"NE","capital":"Lincoln","most-populous-city":"Omaha","population":"1796619","square-miles":"77358","time-zone-1":"CST (UTC-6)","time-zone-2":"MT (UTC-07)","dst":"YES"},
{"name":"Nevada","abbr":"NV","capital":"Carson City","most-populous-city":"Las Vegas","population":"2643085","square-miles":"110567","time-zone-1":"PT (UTC-8)","time-zone-2":"MT (UTC-07)","dst":"YES"},
{"name":"New Hampshire","abbr":"NH","capital":"Concord","most-populous-city":"Machester","population":"1324575","square-miles":"9351","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"New Jersey","abbr":"NJ","capital":"Trenton","most-populous-city":"Newark","population":"8707739","square-miles":"8722","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"New Mexico","abbr":"NM","capital":"Santa Fe","most-populous-city":"Albuquerque","population":"2009671","square-miles":"121593","time-zone-1":"MT (UTC-07)","time-zone-2":"","dst":"YES"},
{"name":"New York","abbr":"NY","capital":"Albany","most-populous-city":"New York","population":"19541453","square-miles":"54475","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"North Carolina","abbr":"NC","capital":"Raleigh","most-populous-city":"Charlotte","population":"9380884","square-miles":"53821","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"North Dakota","abbr":"ND","capital":"Bismarck","most-populous-city":"Fargo","population":"646844","square-miles":"70704","time-zone-1":"CST (UTC-6)","time-zone-2":"MT (UTC-07)","dst":"YES"},
{"name":"Ohio","abbr":"OH","capital":"Columbus","most-populous-city":"Columbus","population":"11542645","square-miles":"44828","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Oklahoma","abbr":"OK","capital":"Oklahoma City","most-populous-city":"Oklahoma City","population":"3687050","square-miles":"69903","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"Oregon","abbr":"OR","capital":"Salem","most-populous-city":"Portland","population":"3825657","square-miles":"98386","time-zone-1":"PT (UTC-8)","time-zone-2":"MT (UTC-07)","dst":"YES"},
{"name":"Pennsylvania","abbr":"PA","capital":"Harrisburg","most-populous-city":"Philadelphia","population":"12604767","square-miles":"46058","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Rhode Island","abbr":"RI","capital":"Providence","most-populous-city":"Providence","population":"1053209","square-miles":"1545","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"South Carolina","abbr":"SC","capital":"Columbia","most-populous-city":"Columbia","population":"4561242","square-miles":"32007","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"South Dakota","abbr":"SD","capital":"Pierre","most-populous-city":"Sioux Falls","population":"812383","square-miles":"77121","time-zone-1":"CST (UTC-6)","time-zone-2":"MT (UTC-07)","dst":"YES"},
{"name":"Tennessee","abbr":"TN","capital":"Nashville","most-populous-city":"Memphis","population":"6296254","square-miles":"42146","time-zone-1":"CST (UTC-6)","time-zone-2":"EST (UTC-5)","dst":"YES"},
{"name":"Texas","abbr":"TX","capital":"Austin","most-populous-city":"Houston","population":"24782302","square-miles":"268601","time-zone-1":"CST (UTC-6)","time-zone-2":"MT (UTC-07)","dst":"YES"},
{"name":"Utah","abbr":"UT","capital":"Salt Lake City","most-populous-city":"Salt Lake City","population":"2784572","square-miles":"84904","time-zone-1":"MT (UTC-07)","time-zone-2":"","dst":"YES"},
{"name":"Vermont","abbr":"VT","capital":"Montpelier","most-populous-city":"Burlington","population":"621760","square-miles":"9615","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Virginia","abbr":"VA","capital":"Richmond","most-populous-city":"Virginia Beach","population":"7882590","square-miles":"42769","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Washington","abbr":"WA","capital":"Olympia","most-populous-city":"Seattle","population":"6664195","square-miles":"71303","time-zone-1":"PT (UTC-8)","time-zone-2":"","dst":"YES"},
{"name":"West Virginia","abbr":"WV","capital":"Charleston","most-populous-city":"Charleston","population":"1819777","square-miles":"24231","time-zone-1":"EST (UTC-5)","time-zone-2":"","dst":"YES"},
{"name":"Wisconsin","abbr":"WI","capital":"Madison","most-populous-city":"Milwaukee","population":"5654774","square-miles":"65503","time-zone-1":"CST (UTC-6)","time-zone-2":"","dst":"YES"},
{"name":"Wyoming","abbr":"WY","capital":"Cheyenne","most-populous-city":"Cheyenne","population":"544270","square-miles":"97818","time-zone-1":"MT (UTC-07)","time-zone-2":"","dst":"YES"}
];

module.exports = states;